using System;

namespace XrmToolBox.DataverseAnonymizer.DataSources
{
    public class QuotesDataSource
    {
        private static Random random = new Random();

        private static string[] quotes = new string[]
        {
            "To be, or not to be, that is the question...",
            "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.",
            "I have not failed. I've just found 10,000 ways that won't work.",
            "Success is not final, failure is not fatal: It is the courage to continue that counts.",
            "The journey of a thousand miles begins with one step.",
            "In three words I can sum up everything I've learned about life: It goes on.",
            "You only live once, but if you do it right, once is enough.",
            "Life is what happens when you're busy making other plans.",
            "The future belongs to those who believe in the beauty of their dreams.",
            "Everything you can imagine is real.",
            "Believe you can and you're halfway there.",
            "The only limit to our realization of tomorrow will be our doubts of today.",
            "The only thing we have to fear is fear itself.",
            "It does not matter how slowly you go as long as you do not stop.",
            "What we think, we become.",
            "We become what we think about.",
            "Whatever you are, be a good one.",
            "Dream big and dare to fail.",
            "You are never too old to set another goal or to dream a new dream.",
            "The best time to plant a tree was 20 years ago. The second best time is now.",
            "The mind is everything. What you think you become.",
            "Keep your face always toward the sunshine—and shadows will fall behind you.",
            "It is never too late to be what you might have been.",
            "In the end, it's not the years in your life that count. It's the life in your years.",
            "Life is a journey, not a destination.",
            "A journey of a thousand miles begins with a single step.",
            "Happiness is not something readymade. It comes from your own actions.",
            "The only person you should try to be better than is the person you were yesterday.",
            "Success is not the key to happiness. Happiness is the key to success.",
            "You miss 100% of the shots you don't take.",
            "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
            "Don't watch the clock; do what it does. Keep going.",
            "The only way to achieve the impossible is to believe it is possible.",
            "The future depends on what you do today.",
            "You are braver than you believe, stronger than you seem, and smarter than you think.",
            "It always seems impossible until it's done.",
            "Life is what happens when you're busy making other plans.",
            "The only place where success comes before work is in the dictionary.",
            "You are never too old to set another goal or to dream a new dream.",
            "Either you run the day, or the day runs you.",
            "Don't wait. The time will never be just right.",
            "Believe you can and you're halfway there.",
            "The only limit to our realization of tomorrow will be our doubts of today.",
            "A journey of a thousand miles begins with a single step.",
            "It's not whether you get knocked down, it's whether you get up.",
            "Your time is limited, don't waste it living someone else's life.",
            "The greatest glory in living lies not in never falling, but in rising every time we fall.",
            "In the end, it's not the years in your life that count. It's the life in your years.",
            "Life is what happens when you're busy making other plans.",
            "Go confidently in the direction of your dreams. Live the life you have imagined.",
            "You are never too old to set another goal or to dream a new dream.",
            "The future belongs to those who believe in the beauty of their dreams.",
            "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.",
            "The best way to predict the future is to create it.",
            "The only person you should try to be better than is the person you were yesterday.",
            "It is never too late to be what you might have been.",
            "The only way to achieve the impossible is to believe it is possible.",
            "You must be the change you wish to see in the world.",
            "Success is not the key to happiness. Happiness is the key to success.",
            "You miss 100% of the shots you don't take.",
            "Life is like riding a bicycle. To keep your balance, you must keep moving.",
            "It always seems impossible until it's done.",
            "Success is not final, failure is not fatal: It is the courage to continue that counts.",
            "Our greatest glory is not in never falling, but in rising every time we fall.",
            "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
            "Believe you can and you're halfway there.",
            "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
            "The only limit to our realization of tomorrow will be our doubts of today.",
            "The future belongs to those who believe in the beauty of their dreams.",
            "The mind is everything. What you think you become.",
            "Success is not the key to happiness. Happiness is the key to success.",
            "Everything you can imagine is real.",
            "What we think, we become.",
            "You miss 100% of the shots you don't take.",
            "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.",
            "The best time to plant a tree was 20 years ago. The second best time is now.",
            "The only thing we have to fear is fear itself.",
            "Life is like riding a bicycle. To keep your balance, you must keep moving.",
            "It always seems impossible until it's done.",
            "The mind is everything. What you think you become.",
            "Keep your face always toward the sunshine—and shadows will fall behind you.",
            "It is never too late to be what you might have been.",
            "Believe you can and you're halfway there.",
            "The only way to achieve the impossible is to believe it is possible.",
            "Success is not the key to happiness. Happiness is the key to success.",
            "You miss 100% of the shots you don't take.",
            "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
            "Don't watch the clock; do what it does. Keep going.",
            "The only way to achieve the impossible is to believe it is possible.",
            "The future depends on what you do today."
        };

        public static string GetQuote()
        {
            return quotes[random.Next(0, quotes.Length)];
        }
    }
}
